package be.isach.ultracosmetics.v1_19_R1;

/**
 * This file automatically generated by obfuscatedfields_generator.py in tooling folder
 */
public class ObfuscatedFields {
    // corresponds to net.minecraft.world.entity.LivingEntity#jumping
    public static final String JUMPING = "%placeholder%";
    // corresponds to net.minecraft.world.entity.ai.navigation.PathNavigation#isInLiquid()
    public static final String IS_IN_LIQUID = "%placeholder%";
    // corresponds to net.minecraft.world.entity.ai.Brain#memories
    public static final String MEMORIES = "%placeholder%";
    // corresponds to net.minecraft.world.entity.ai.Brain#sensors
    public static final String SENSORS = "%placeholder%";
    // corresponds to net.minecraft.world.entity.ai.goal.GoalSelector#lockedFlags
    public static final String LOCKED_FLAGS = "%placeholder%";
    // corresponds to net.minecraft.world.entity.ai.goal.GoalSelector#disabledFlags
    public static final String DISABLED_FLAGS = "%placeholder%";
    // corresponds to net.minecraft.core.MappedRegistry#frozen
    public static final String FROZEN = "%placeholder%";
    // corresponds to net.minecraft.core.MappedRegistry#intrusiveHolderCache
    public static final String INTRUSIVE_HOLDER_CACHE = "%placeholder%";

    private ObfuscatedFields() {
    };
}
