name: UltraCosmetics
version: 2.0
author: iSach
load: POSTWORLD
main: be.isach.ultracosmetics.Core
depend: [Hub]
softdepend: [LibsDisguises, NoteBlockAPI, Vault]
commands:
  ultracosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics
permissions:
  ultracosmetics.*:
    children:
      - ultracosmetics.gadgets.*
      - ultracosmetics.pets.*
      - ultracosmetics.particleeffecs.*
      - ultracosmetics.mounts.*
      - ultracosmetics.morphs.*
      - ultracosmetics.commands.*
      - ultracosmetics.openmenu
  ultracosmetics.openmenu:
   default: true
  ultracosmetics.receivechest:
   default: true
  ultracosmetics.commands.*:
    children:
      - ultracosmetics.commands.reload
      - ultracosmetics.commands.clear
      - ultracosmetics.commands.clear.others
      - ultracosmetics.commands.toggle
      - ultracosmetics.commands.toggle.others
      - ultracosmetics.commands.give
      - ultracosmetics.commands.chest
      - ultracosmetics.commands.others
  ultracosmetics.commands.reload:
    default: op
  ultracosmetics.commands.clear:
    default: op
  ultracosmetics.commands.clear.others:
    default: op
  ultracosmetics.commands.toggle:
    default: op
  ultracosmetics.commands.toggle.others:
    default: op
  ultracosmetics.commands.give:
    default: op
  ultracosmetics.commands.chest:
    default: op
  ultracosmetics.commands.others:
    default: op
  ultracosmetics.gadgets.*:
    children: 
      - ultracosmetics.gadgets.paintballgun
      - ultracosmetics.gadgets.batblaster
      - ultracosmetics.gadgets.chickenator
      - ultracosmetics.gadgets.melonthrower
      - ultracosmetics.gadgets.etherealpearl
      - ultracosmetics.gadgets.discoball
      - ultracosmetics.gadgets.colorbomb
      - ultracosmetics.gadgets.fleshhook
      - ultracosmetics.gadgets.portalgun
      - ultracosmetics.gadgets.blizzardblaster
      - ultracosmetics.gadgets.thorhammer
      - ultracosmetics.gadgets.smashdown
      - ultracosmetics.gadgets.explosivesheep
      - ultracosmetics.gadgets.antigravity
      - ultracosmetics.gadgets.tsunami
      - ultracosmetics.gadgets.rocket
      - ultracosmetics.gadgets.tnt
      - ultracosmetics.gadgets.blackhole
      - ultracosmetics.gadgets.fungun
      - ultracosmetics.gadgets.quakegun
      - ultracosmetics.gadgets.parachute
      - ultracosmetics.gadgets.ghostparty
      - ultracosmetics.gadgets.firework
      - ultracosmetics.gadgets.christmastree
  ultracosmetics.gadgets.paintballgun:
    default: op
  ultracosmetics.gadgets.batblaster:
    default: op
  ultracosmetics.gadgets.chickenator:
    default: op
  ultracosmetics.gadgets.melonthrower:
    default: op
  ultracosmetics.gadgets.etherealpearl:
    default: op
  ultracosmetics.gadgets.discoball:
    default: op
  ultracosmetics.gadgets.colorbomb:
    default: op
  ultracosmetics.gadgets.fleshhook:
    default: op
  ultracosmetics.gadgets.portalgun:
    default: op
  ultracosmetics.gadgets.blizzardblaster:
    default: op
  ultracosmetics.gadgets.thorhammer:
    default: op
  ultracosmetics.gadgets.smashdown:
    default: op
  ultracosmetics.gadgets.explosivesheep:
    default: op
  ultracosmetics.gadgets.antigravity:
    default: op
  ultracosmetics.gadgets.tsunami:
    default: op
  ultracosmetics.gadgets.rocket:
    default: op
  ultracosmetics.gadgets.tnt:
    default: op
  ultracosmetics.gadgets.blackhole:
    default: op
  ultracosmetics.gadgets.parachute:
    default: op
  ultracosmetics.gadgets.quakegun:
    default: op
  ultracosmetics.gadgets.fungun:
    default: op
  ultracosmetics.gadgets.ghostparty:
    default: op
  ultracosmetics.gadgets.firework:
    default: op
  ultracosmetics.gadgets.christmastree:
    default: op
  ultracosmetics.particleeffecs.*:
    children:
      - ultracosmetics.particleeffects.raincloud
      - ultracosmetics.particleeffects.snowcloud
      - ultracosmetics.particleeffects.bloodhelix
      - ultracosmetics.particleeffects.frostlord
      - ultracosmetics.particleeffects.flamerings
      - ultracosmetics.particleeffects.inlove
      - ultracosmetics.particleeffects.greensparks
      - ultracosmetics.particleeffects.enchanted
      - ultracosmetics.particleeffects.inferno
      - ultracosmetics.particleeffects.frozenwalk
      - ultracosmetics.particleeffects.music
      - ultracosmetics.particleeffects.angelwings
      - ultracosmetics.particleeffects.superhero
      - ultracosmetics.particleeffects.santahat
  ultracosmetics.particleeffects.raincloud:
    default: op
  ultracosmetics.particleeffects.snowcloud:
    default: op
  ultracosmetics.particleeffects.bloodhelix:
    default: op
  ultracosmetics.particleeffects.frostlord:
    default: op
  ultracosmetics.particleeffects.flamerings:
    default: op
  ultracosmetics.particleeffects.inlove:
    default: op
  ultracosmetics.particleeffects.greensparks:
    default: op
  ultracosmetics.particleeffects.music:
    default: op
  ultracosmetics.particleeffects.frozenwalk:
    default: op
  ultracosmetics.particleeffects.inferno:
    default: op
  ultracosmetics.particleeffects.enchanted:
    default: op
  ultracosmetics.particleeffects.angelwings:
    default: op
  ultracosmetics.particleeffects.superhero:
    default: op
  ultracosmetics.particleeffects.santahat:
    default: op
  ultracosmetics.mounts.*:
    children:
      - ultracosmetics.mounts.druggedhorse
      - ultracosmetics.mounts.ecologisthorse
      - ultracosmetics.mounts.glacialsteed
      - ultracosmetics.mounts.infernalhorror
      - ultracosmetics.mounts.mountoffire
      - ultracosmetics.mounts.mountofwater
      - ultracosmetics.mounts.walkingdead
      - ultracosmetics.mounts.snake
      - ultracosmetics.mounts.nyansheep
      - ultracosmetics.mounts.dragon
      - ultracosmetics.mounts.skysquid
      - ultracosmetics.mounts.slime
      - ultracosmetics.mounts.hypecart
      - ultracosmetics.mounts.spider
      - ultracosmetics.mounts.rudolph
  ultracosmetics.mounts.druggedhorse:
    default: op
  ultracosmetics.mounts.ecologisthorse:
    default: op
  ultracosmetics.mounts.glacialsteed:
    default: op
  ultracosmetics.mounts.infernalhorror:
    default: op
  ultracosmetics.mounts.mountoffire:
    default: op
  ultracosmetics.mounts.mountofwater:
    default: op
  ultracosmetics.mounts.walkingdead:
    default: op
  ultracosmetics.mounts.snake:
    default: op
  ultracosmetics.mounts.nyansheep:
    default: op
  ultracosmetics.mounts.dragon:
    default: op
  ultracosmetics.mounts.skysquid:
    default: op
  ultracosmetics.mounts.slime:
    default: op
  ultracosmetics.mounts.hypecart:
    default: op
  ultracosmetics.mounts.spider:
    default: op
  ultracosmetics.mounts.rudolph:
    default: op
  ultracosmetics.pets.*:
    children:
      - ultracosmetics.pets.piggy
      - ultracosmetics.pets.sheep
      - ultracosmetics.pets.kitty
      - ultracosmetics.pets.dog
      - ultracosmetics.pets.chick
      - ultracosmetics.pets.cow
      - ultracosmetics.pets.easterbunny
      - ultracosmetics.pets.wither
      - ultracosmetics.pets.pumpling
      - ultracosmetics.pets.christmaself
      - ultracosmetics.pets.rename
  ultracosmetics.pets.piggy:
    default: op
  ultracosmetics.pets.sheep:
    default: op
  ultracosmetics.pets.kitty:
    default: op
  ultracosmetics.pets.dog:
    default: op
  ultracosmetics.pets.chick:
    default: op
  ultracosmetics.pets.cow:
    default: op
  ultracosmetics.pets.easterbunny:
    default: op
  ultracosmetics.pets.wither:
    default: op
  ultracosmetics.pets.pumpling:
    default: op
  ultracosmetics.pets.rename:
    default: op
  ultracosmetics.pets.christmaself:
    default: op
  ultracosmetics.morphs.*:
    children:
      - ultracosmetics.morphs.bat
      - ultracosmetics.morphs.blaze
      - ultracosmetics.morphs.pig
      - ultracosmetics.morphs.chicken
      - ultracosmetics.morphs.slime
      - ultracosmetics.morphs.enderman
      - ultracosmetics.morphs.creeper
      - ultracosmetics.morphs.witherskeleton
      - ultracosmetics.morphs.snowman
  ultracosmetics.morphs.bat:
    default: op
  ultracosmetics.morphs.blaze:
    default: op
  ultracosmetics.morphs.pig:
    default: op
  ultracosmetics.morphs.chicken:
    default: op
  ultracosmetics.morphs.slime:
    default: op
  ultracosmetics.morphs.enderman:
    default: op
  ultracosmetics.morphs.creeper:
    default: op
  ultracosmetics.morphs.witherskeleton:
    default: op
  ultracosmetics.morphs.snowman:
    default: op
  ultracosmetics.hats.*:
    children:
      - ultracosmetics.hats.astronaut
      - ultracosmetics.hats.scared
      - ultracosmetics.hats.angel
      - ultracosmetics.hats.embarassed
      - ultracosmetics.hats.kissy
      - ultracosmetics.hats.sad
      - ultracosmetics.hats.cool
      - ultracosmetics.hats.surprised
      - ultracosmetics.hats.dead
      - ultracosmetics.hats.crying
      - ultracosmetics.hats.bigsmile
      - ultracosmetics.hats.wink
      - ultracosmetics.hats.derp
      - ultracosmetics.hats.smile
      - ultracosmetics.hats.iron
      - ultracosmetics.hats.gold
      - ultracosmetics.hats.diamond
      - ultracosmetics.hats.piston
      - ultracosmetics.hats.commandblock
      - ultracosmetics.hats.music
      - ultracosmetics.hats.squid
      - ultracosmetics.hats.chicken
      - ultracosmetics.hats.pig
      - ultracosmetics.hats.blaze
      - ultracosmetics.hats.sheep
      - ultracosmetics.hats.golem
      - ultracosmetics.hats.enderman
      - ultracosmetics.hats.mario
      - ultracosmetics.hats.luigi
      - ultracosmetics.hats.batman
      - ultracosmetics.hats.chest
      - ultracosmetics.hats.skull
      - ultracosmetics.hats.ghost
      - ultracosmetics.hats.jackolantern
      - ultracosmetics.hats.scaryclown
      - ultracosmetics.hats.santa
      - ultracosmetics.hats.snowman
      - ultracosmetics.hats.present
      - ultracosmetics.hats.elf
  ultracosmetics.hats.astronaut:
    default: op
  ultracosmetics.hats.scared:
    default: op
  ultracosmetics.hats.angel:
    default: op
  ultracosmetics.hats.embarassed:
    default: op
  ultracosmetics.hats.kissy:
    default: op
  ultracosmetics.hats.sad:
    default: op
  ultracosmetics.hats.cool:
    default: op
  ultracosmetics.hats.surprised:
    default: op
  ultracosmetics.hats.dead:
    default: op
  ultracosmetics.hats.crying:
    default: op
  ultracosmetics.hats.bigsmile:
    default: op
  ultracosmetics.hats.wink:
    default: op
  ultracosmetics.hats.derp:
    default: op
  ultracosmetics.hats.smile:
    default: op
  ultracosmetics.hats.iron:
    default: op
  ultracosmetics.hats.gold:
    default: op
  ultracosmetics.hats.diamond:
    default: op
  ultracosmetics.hats.piston:
    default: op
  ultracosmetics.hats.commandblock:
    default: op
  ultracosmetics.hats.music:
    default: op
  ultracosmetics.hats.squid:
    default: op
  ultracosmetics.hats.chicken:
    default: op
  ultracosmetics.hats.pig:
    default: op
  ultracosmetics.hats.blaze:
    default: op
  ultracosmetics.hats.sheep:
    default: op
  ultracosmetics.hats.golem:
    default: op
  ultracosmetics.hats.enderman:
    default: op
  ultracosmetics.hats.mario:
    default: op
  ultracosmetics.hats.luigi:
    default: op
  ultracosmetics.hats.batman:
    default: op
  ultracosmetics.hats.chest:
    default: op
  ultracosmetics.hats.skull:
    default: op
  ultracosmetics.hats.ghost:
    default: op
  ultracosmetics.hats.jackolantern:
    default: op
  ultracosmetics.hats.scaryclown:
    default: op
  ultracosmetics.hats.santa:
    default: op
  ultracosmetics.hats.snowman:
    default: op
  ultracosmetics.hats.present:
    default: op
  ultracosmetics.hats.elf:
    default: op