name: UltraCosmetics
version: @VERSION@
author: iSach
load: POSTWORLD
main: be.isach.ultracosmetics.UltraCosmetics
api-version: 1.13
softdepend:
- LibsDisguises
- Vault
- PlaceholderAPI
- PlayerPoints
- WorldGuard
- Essentials
- LuckPerms
commands:
  ultracosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics
permissions:
  ultracosmetics.openmenu:
    default: true
  ultracosmetics.receivechest:
    default: true
  ultracosmetics.treasurechests.buykey:
    default: true
  ultracosmetics.bypass.disabledcommands:
    default: op
  ultracosmetics.bypass.cooldown:
    default: false
